matrix:
  include:
    - os: osx
      osx_image: xcode11.3
      language: node_js
      node_js: "12.8.1"
      env:
        - npm_config_target=$nct
        - npm_config_arch=$nca
        - npm_config_target_arch=$ncta
        - npm_config_disturl=$ncd
        - npm_config_runtime=$ncr
        - npm_config_build_from_source=$ncbfs
    - os: linux
      language: node_js
      node_js: "12.8.1"
      env: 
        - npm_config_target=$nct
        - npm_config_arch=$nca
        - npm_config_target_arch=$ncta
        - npm_config_disturl=$ncd
        - npm_config_runtime=$ncr
        - npm_config_build_from_source=$ncbfs
      addons:
        apt:
          packages:
          - libudev-dev
cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

# if: tag IS present

script:
  - npm run build

before_deploy:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then rm -fr ~/private_keys && mkdir ~/private_keys                                    ; fi 
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then echo $AUTH_PRIVATE_KEY | base64 -D > ~/private_keys/AuthKey_${APPLE_API_KEY}.p8  ; fi 

deploy:
  - provider: script
    script: npm run build
    skip_cleanup: true
    on:
      tags: true
